In [1]:
import tensorflow as tf
#indexing

In [2]:
tf_indexed = tf.constant([1,2,3,4,5,5,6,7])
tf_indexed

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 5, 6, 7])>

In [3]:
tf_indexed[0:5]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [4]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [9]:
tf_indexed[3:-1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 5, 6])>

In [10]:
#indexing in 2d tensors
tensor_two_d = tf.constant([
    [1,2,3],
    [5,6,7],
    [8,9,10]
]
)
tensor_two_d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])>

In [12]:
tensor_two_d[0:2,0:3]   # [row,col]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [13]:
tensor_two_d[0:2,:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [14]:
tensor_two_d[2,1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 10])>

In [16]:
tensor_two_d[2,0]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [17]:
tensor_two_d[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 8])>

In [18]:
#indexing in 3d tensors
tensor_three_d = tf.constant([
    [[1,2,3],
    [5,6,7]],
    
    [[1,2,3],
    [5,6,7]],
    
    [[1,2,3],
    [5,6,7]]
])
tensor_three_d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])>

In [19]:
tensor_three_d[0,:,:] # [2d_index,row,col]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [23]:
tensor_three_d[0,1,1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 7])>

# lecture 07 - Math operations in tensorflow

In [26]:
 x_abs = tf.constant([2.25,-3.56],dtype=tf.float16)
 tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.25, 3.56], dtype=float16)>

In [27]:
complex_abs = tf.constant([-2.25+4.75j])
tf.abs(complex_abs)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [29]:
tf.sqrt((-2.25)**2 + 4.75**2 )

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [33]:
x_1 = tf.constant([5,4,3,2,1])
x_2 =tf.constant([1,2,3,0,5])

tf.add(x_1,x_2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([6, 6, 6, 2, 6])>

In [31]:
tf.multiply(x_1,x_2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 8, 9, 8, 5])>

In [34]:
tf.divide(x_1,x_2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([5. , 2. , 1. , inf, 0.2])>

In [36]:
tf.math.divide_no_nan(x_1,x_2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([5. , 2. , 1. , 0. , 0.2])>

In [38]:
x_3 = tf.constant([7]) #broadcasting
tf.add(x_1,x_3)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([12, 11, 10,  9,  8])>

In [39]:
tf.multiply(x_3,x_1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([35, 28, 21, 14,  7])>

In [40]:
#tf.math.argmax - returns the index of max value

amax = tf.constant([1,2,3,4,5,6,100,10])
tf.math.argmax(amax)# returns 100's index i.e 6

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [ ]:
#for 2d tensor we can specify axis - 0 means vertical axis
#simillar for argmin

In [41]:
x = tf.constant([-128.0, 0.0, 128.0], dtype=tf.float32)
tf.sigmoid(x)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0. , 0.5, 1. ], dtype=float32)>

### practice questions

### Tensor Indexing

1. **Create a Tensor and Slice It**
   - Create a 3x3 tensor with values ranging from 1 to 9. Extract the second row.

2. **Modify Specific Elements**
   - Create a 4x4 tensor with values ranging from 1 to 16. Replace the elements in the second column with zeros.

3. **Extract Sub-Tensor**
   - Create a 3x3x3 tensor with values from a normal distribution. Extract a 2x2x2 sub-tensor from it.

4. **Advanced Slicing**
   - Create a 5x5 tensor with values from 1 to 25. Extract every second row and column.

5. **Masking Elements**
   - Create a 1D tensor with values from 0 to 9. Replace all elements that are greater than 5 with -1.

### Mathematical Operations

6. **Element-wise Addition**
   - Create two 3x3 tensors with values ranging from 1 to 9 and 10 to 18 respectively. Perform element-wise addition.

7. **Matrix Multiplication**
   - Create a 2x3 tensor and a 3x2 tensor. Perform matrix multiplication.

8. **Element-wise Operations**
   - Create a 4x4 tensor with values from 1 to 16. Compute the element-wise square of the tensor.

9. **Broadcasting and Addition**
   - Create a 3x1 tensor and a 1x3 tensor. Add them using broadcasting to get a 3x3 result.

10. **Reduction Operations**
    - Create a 4x4 tensor with values from 1 to 16. Compute the sum of all elements and the mean of all elements.

These questions should help you practice and understand tensor indexing and mathematical operations in TensorFlow. Happy coding!

In [42]:
#1
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
tensor_two_d[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [53]:
tensor_two_d = tf.Variable([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
)
tensor_two_d[:,1].assign(tf.zeros(4))

ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [50]:
three_d = tf.constant([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
])
three_d[0:2,0:2,0:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])>

In [55]:
tensor_two_d = tf.constant([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
]
)
tensor_two_d[::2,::2]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])>

In [56]:
#5 no questions solution

tensor = tf.constant([1,2,3,4,5,6,6,7,9,10])

tf_masked = tf.where(tensor>5,-1,tensor)
tf_masked 

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1])>

In [57]:
#6
x =  tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)

y =  tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
tf.add(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])>

In [58]:
#8 
square = tf.constant([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
]
)
tf.square(square)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])>

In [59]:
import tensorflow as tf

tensor = tf.constant([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])
total_sum = tf.reduce_sum(tensor)
mean_value = tf.reduce_mean(tensor)
print(f"Sum: {total_sum}, Mean: {mean_value}")


Sum: 136, Mean: 8
