In [1]:
import tensorflow as tf
#indexing

In [2]:
tf_indexed = tf.constant([1,2,3,4,5,5,6,7])
tf_indexed

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 5, 6, 7])>

In [3]:
tf_indexed[0:5]

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [4]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [9]:
tf_indexed[3:-1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 5, 6])>

In [10]:
#indexing in 2d tensors
tensor_two_d = tf.constant([
    [1,2,3],
    [5,6,7],
    [8,9,10]
]
)
tensor_two_d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])>

In [12]:
tensor_two_d[0:2,0:3]   # [row,col]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [13]:
tensor_two_d[0:2,:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [14]:
tensor_two_d[2,1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 10])>

In [16]:
tensor_two_d[2,0]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [17]:
tensor_two_d[:,0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 5, 8])>

In [18]:
#indexing in 3d tensors
tensor_three_d = tf.constant([
    [[1,2,3],
    [5,6,7]],
    
    [[1,2,3],
    [5,6,7]],
    
    [[1,2,3],
    [5,6,7]]
])
tensor_three_d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]])>

In [19]:
tensor_three_d[0,:,:] # [2d_index,row,col]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [23]:
tensor_three_d[0,1,1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 7])>

# lecture 07 - Math operations in tensorflow

In [26]:
 x_abs = tf.constant([2.25,-3.56],dtype=tf.float16)
 tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.25, 3.56], dtype=float16)>

In [27]:
complex_abs = tf.constant([-2.25+4.75j])
tf.abs(complex_abs)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [29]:
tf.sqrt((-2.25)**2 + 4.75**2 )

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [33]:
x_1 = tf.constant([5,4,3,2,1])
x_2 =tf.constant([1,2,3,0,5])

tf.add(x_1,x_2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([6, 6, 6, 2, 6])>

In [31]:
tf.multiply(x_1,x_2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 8, 9, 8, 5])>

In [34]:
tf.divide(x_1,x_2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([5. , 2. , 1. , inf, 0.2])>

In [36]:
tf.math.divide_no_nan(x_1,x_2)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([5. , 2. , 1. , 0. , 0.2])>

In [38]:
x_3 = tf.constant([7]) #broadcasting
tf.add(x_1,x_3)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([12, 11, 10,  9,  8])>

In [39]:
tf.multiply(x_3,x_1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([35, 28, 21, 14,  7])>

In [40]:
#tf.math.argmax - returns the index of max value

amax = tf.constant([1,2,3,4,5,6,100,10])
tf.math.argmax(amax)# returns 100's index i.e 6

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [ ]:
#for 2d tensor we can specify axis - 0 means vertical axis
#simillar for argmin

In [41]:
x = tf.constant([-128.0, 0.0, 128.0], dtype=tf.float32)
tf.sigmoid(x)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0. , 0.5, 1. ], dtype=float32)>

### practice questions

### Tensor Indexing

1. **Create a Tensor and Slice It**
   - Create a 3x3 tensor with values ranging from 1 to 9. Extract the second row.

2. **Modify Specific Elements**
   - Create a 4x4 tensor with values ranging from 1 to 16. Replace the elements in the second column with zeros.

3. **Extract Sub-Tensor**
   - Create a 3x3x3 tensor with values from a normal distribution. Extract a 2x2x2 sub-tensor from it.

4. **Advanced Slicing**
   - Create a 5x5 tensor with values from 1 to 25. Extract every second row and column.

5. **Masking Elements**
   - Create a 1D tensor with values from 0 to 9. Replace all elements that are greater than 5 with -1.

### Mathematical Operations

6. **Element-wise Addition**
   - Create two 3x3 tensors with values ranging from 1 to 9 and 10 to 18 respectively. Perform element-wise addition.

7. **Matrix Multiplication**
   - Create a 2x3 tensor and a 3x2 tensor. Perform matrix multiplication.

8. **Element-wise Operations**
   - Create a 4x4 tensor with values from 1 to 16. Compute the element-wise square of the tensor.

9. **Broadcasting and Addition**
   - Create a 3x1 tensor and a 1x3 tensor. Add them using broadcasting to get a 3x3 result.

10. **Reduction Operations**
    - Create a 4x4 tensor with values from 1 to 16. Compute the sum of all elements and the mean of all elements.

These questions should help you practice and understand tensor indexing and mathematical operations in TensorFlow. Happy coding!

In [42]:
#1
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
tensor_two_d[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6])>

In [53]:
tensor_two_d = tf.Variable([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
)
tensor_two_d[:,1].assign(tf.zeros(4))

ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>

In [50]:
three_d = tf.constant([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
])
three_d[0:2,0:2,0:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])>

In [55]:
tensor_two_d = tf.constant([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
]
)
tensor_two_d[::2,::2]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])>

In [56]:
#5 no questions solution

tensor = tf.constant([1,2,3,4,5,6,6,7,9,10])

tf_masked = tf.where(tensor>5,-1,tensor)
tf_masked 

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5, -1, -1, -1, -1, -1])>

In [57]:
#6
x =  tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)

y =  tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
tf.add(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])>

In [58]:
#8 
square = tf.constant([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
]
)
tf.square(square)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])>

In [59]:
import tensorflow as tf

tensor = tf.constant([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])
total_sum = tf.reduce_sum(tensor)
mean_value = tf.reduce_mean(tensor)
print(f"Sum: {total_sum}, Mean: {mean_value}")


Sum: 136, Mean: 8


# Lecture 08 - Linear Algebra Operations

In [5]:
import tensorflow as tf
x_1 = tf.constant(
    [[1,2,3],
    [3,4,5]]
)
x_2 = tf.constant([
    [5,6,7],
    [9 ,10,11],
    [10,23,60]
])

print(x_1@x_2)# matrix multiplication

tf.Tensor(
[[ 53  95 209]
 [101 173 365]], shape=(2, 3), dtype=int32)


In [6]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4],
       [3, 5]])>

In [9]:
x1 = tf.constant([
    [[1,2],
    [5,6]],
    
    [[1,2],
    [5,6]],
    
    [[1,2],
    [5,6]]
])

x2 =  tf.constant([
    [[1,2,3],
    [5,6,7]],
    
    [[1,2,3],
    [5,6,7]],
    
    [[1,2,3],
    [5,6,7]]
   
])

tf.linalg.matmul(x1,x2)
# 3,2,2   3,2,3  first value should match and rest like 2d matrix (just doing batch multiplication)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[11, 14, 17],
        [35, 46, 57]],

       [[11, 14, 17],
        [35, 46, 57]],

       [[11, 14, 17],
        [35, 46, 57]]])>

In [21]:
#sparse multiplication (if the matrixes are mostlyzeros)

#band_part 

input =tf.constant( [[ 0,  1,  2, 3],
                     [-1,  0,  1, 2],                
                     [-2, -1,  0, 1],
                     [-3, -2, -1, 0]],dtype = tf.float64
)
print(tf.linalg.band_part(input, 0, -1)) #lower triagular

print(tf.linalg.band_part(input, -1, 0) )# upper traingular

# m-n <= lower and n-m <= upper then current value otherwise zero. (n,m)= indexes(i,j)

tf.Tensor(
[[0. 1. 2. 3.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float64)
tf.Tensor(
[[ 0.  0.  0.  0.]
 [-1.  0.  0.  0.]
 [-2. -1.  0.  0.]
 [-3. -2. -1.  0.]], shape=(4, 4), dtype=float64)


tf.Tensor(
[[0. 1. 2. 3.]
 [0. 0. 1. 2.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float64)
tf.Tensor(
[[ 0.  0.  0.  0.]
 [-1.  0.  0.  0.]
 [-2. -1.  0.  0.]
 [-3. -2. -1.  0.]], shape=(4, 4), dtype=float64)


In [43]:
input.shape

TensorShape([4, 4])

In [51]:
x_2 = tf.constant([
    [5,6,7],
    [9 ,10,11],
    [10,23,60]
],dtype= tf.float32)
x_2.shape

TensorShape([3, 3])

In [52]:
x2_inv = tf.linalg.inv(x_2)

x_2@x2_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000037e+00,  3.5762787e-07, -7.0780516e-08],
       [ 3.5762787e-07,  1.0000056e+00,  1.2293458e-07],
       [ 3.3378601e-06,  1.4305115e-06,  9.9999994e-01]], dtype=float32)>

In [55]:
s,u,v = tf.linalg.svd(x_2)
print(s,u,v)

tf.Tensor([67.45648     9.518549    0.14951238], shape=(3,), dtype=float32) tf.Tensor(
[[ 0.14125586  0.46020028 -0.87650603]
 [ 0.2282616   0.8463864   0.4811724 ]
 [ 0.9632983  -0.268041    0.01451099]], shape=(3, 3), dtype=float32) tf.Tensor(
[[ 0.18372759  0.7604174   0.6229042 ]
 [ 0.37484935  0.5316066  -0.75952786]
 [ 0.90869826 -0.3730414   0.18737113]], shape=(3, 3), dtype=float32)


## Tasks

### Easy Questions
1. **Matrix Addition**: Create two matrices of shape (3, 3) and perform matrix addition using TensorFlow.
2. **Matrix Multiplication**: Define two matrices of shape (3, 2) and (2, 3) respectively and compute their product using TensorFlow.
3. **Element-wise Multiplication**: Define two matrices of shape (2, 2) and compute their element-wise product using TensorFlow.
4. **Matrix Transpose**: Create a matrix of shape (4, 3) and find its transpose using TensorFlow.
5. **Trace of a Matrix**: Define a square matrix of shape (3, 3) and compute its trace (sum of diagonal elements) using TensorFlow.

### Medium Questions
1. **Determinant of a Matrix**: Define a square matrix of shape (3, 3) and calculate its determinant using TensorFlow.
2. **Inverse of a Matrix**: Create a square matrix of shape (3, 3) and find its inverse using TensorFlow.
3. **Eigenvalues and Eigenvectors**: Define a square matrix of shape (2, 2) and compute its eigenvalues and eigenvectors using TensorFlow.
4. **Singular Value Decomposition (SVD)**: Perform singular value decomposition on a matrix of shape (3, 3) using TensorFlow.
5. **Solving Linear System of Equations**: Given a system of linear equations represented by \(Ax = b\), where A is a matrix of shape (3, 3) and b is a vector of shape (3, 1), solve for x using TensorFlow.

### Hard Questions
1. **Matrix Exponential**: Compute the exponential of a square matrix of shape (2, 2) using TensorFlow.
2. **QR Decomposition**: Perform QR decomposition on a matrix of shape (4, 3) using TensorFlow.
3. **Cholesky Decomposition**: Create a positive definite matrix of shape (3, 3) and perform Cholesky decomposition using TensorFlow.
4. **Frobenius Norm**: Compute the Frobenius norm of a matrix of shape (3, 3) using TensorFlow.
5. **Tensor Decomposition (CP Decomposition)**: Perform CANDECOMP/PARAFAC (CP) decomposition on a 3-dimensional tensor of shape (3, 3, 3) using TensorFlow.

Feel free to reach out if you need further clarification or examples for any of these questions!

In [61]:
# Easy
#4
x =  tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
]
)
print(tf.transpose(x))

#5
xt=  tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
tf.linalg.trace(x)



tf.Tensor(
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [66]:
#Medium hard
#1
xd =  tf.constant([
    [7,2,3],
    [4,5,6],
    [7,8,90]
],dtype = tf.float32
)
print(tf.linalg.det(xd))

#3
eval ,evec = tf.linalg.eig(xd)
print(eval,evec)



tf.Tensor(2168.9993, shape=(), dtype=float32)
tf.Tensor([ 8.280773 +0.j  2.8835719+0.j 90.83565  +0.j], shape=(3,), dtype=complex64) tf.Tensor(
[[ 0.73672456+0.j  0.40602392+0.j  0.03737161+0.j]
 [ 0.6639474 +0.j -0.91242903+0.j  0.0714151 +0.j]
 [-0.1281051 +0.j  0.05116452+0.j  0.9967463 +0.j]], shape=(3, 3), dtype=complex64)


In [67]:
#5
A = tf.constant([[3.0, 1.0, 2.0], 
                 [1.0, 2.0, 3.0], 
                 [2.0, 3.0, 1.0]])
b = tf.constant([[1.0], [1.0], [1.0]])

# Solve for x in Ax = b
x = tf.linalg.solve(A, b)

print("Solution x of the linear system Ax = b:\n", x.numpy())

Solution x of the linear system Ax = b:
 [[0.16666669]
 [0.16666666]
 [0.16666666]]


In [68]:
#Hard Questions
#1
xd =  tf.constant([
    [7,2,3],
    [4,5,6],
    [7,8,90]
],dtype = tf.float32
)
print("Exponetial of a matrix",tf.linalg.expm(xd))

Exponetial of a matrix tf.Tensor(
[[9.2094822e+36 9.9638148e+36 1.0460394e+38]
 [1.7598850e+37 1.9040341e+37 1.9989278e+38]
 [2.4562840e+38 2.6574739e+38           inf]], shape=(3, 3), dtype=float32)


In [77]:
x =  tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
],dtype=tf.float32
)
q,r = tf.linalg.qr(x)
print(q,r)

tf.Tensor(
[[-0.07761502 -0.8330517   0.52171254]
 [-0.31046018 -0.45123714 -0.57130194]
 [-0.54330534 -0.06942132 -0.42253062]
 [-0.7761505   0.31239498  0.47212094]], shape=(4, 3), dtype=float32) tf.Tensor(
[[-1.2884099e+01 -1.4591629e+01 -1.6299160e+01]
 [ 0.0000000e+00 -1.0413142e+00 -2.0826297e+00]
 [ 0.0000000e+00  0.0000000e+00  7.9968021e-07]], shape=(3, 3), dtype=float32)


In [78]:
import tensorflow as tf

# Define a positive definite matrix
A = tf.constant([[4.0, 1.0, 2.0], 
                 [1.0, 3.0, 0.5], 
                 [2.0, 0.5, 3.0]])

# Perform Cholesky decomposition
L = tf.linalg.cholesky(A)

print("Cholesky decomposition (L) of matrix A:\n", L.numpy())


Cholesky decomposition (L) of matrix A:
 [[2.        0.        0.       ]
 [0.5       1.6583124 0.       ]
 [1.        0.        1.4142135]]


In [80]:
import tensorflow as tf

# Define a matrix
A = tf.constant([[1.0, 2.0, 3.0], 
                 [4.0, 5.0, 6.0], 
                 [7.0, 8.0, 9.0]])

# Compute the Frobenius norm
frobenius_norm = tf.norm(A, ord='fro')

print("Frobenius norm of matrix A:", frobenius_norm.numpy())


ValueError: 'ord' must be a supported vector norm, got fro

In [81]:
pip install tensorly



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



   ---------------------------------------- 0.0/229.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/229.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/229.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/229.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/229.7 kB ? eta -:--:--
   ---------------------------------------- 0.0/229.7 kB ? eta -:--:--
   ------- -------------------------------- 41.0/229.7 kB ? eta -:--:--
   -------- ------------------------------ 51.2/229.7 kB 435.7 kB/s eta 0:00:01
   -------- ------------------------------ 51.2/229.7 kB 435.7 kB/s eta 0:00:01
   -------- ------------------------------ 51.2/229.7 kB 435.7 kB/s eta 0:00:01
   -------- ------------------------------ 51.2/229.7 kB 435.7 kB/s eta 0:00:01
   -------- ------------------------------ 51.2/229.7 kB 435.7 kB/s eta 0:00:01
   -------- ------------------------------ 51.2/229.7 kB 435.7 kB/s eta 0:00:01
   -------- ---------

In [82]:
import tensorflow as tf
import tensorly as tl
from tensorly.decomposition import parafac

# Set TensorFlow as the backend for TensorLy
tl.set_backend('tensorflow')

# Define a 3-dimensional tensor
tensor = tf.constant([[[1.0, 2.0, 3.0], 
                       [4.0, 5.0, 6.0], 
                       [7.0, 8.0, 9.0]],
                      
                      [[10.0, 11.0, 12.0], 
                       [13.0, 14.0, 15.0], 
                       [16.0, 17.0, 18.0]],
                      
                      [[19.0, 20.0, 21.0], 
                       [22.0, 23.0, 24.0], 
                       [25.0, 26.0, 27.0]]])

# Perform CP decomposition
factors = parafac(tensor, rank=3)

# Print the factors
print("CP decomposition factors:")
for i, factor in enumerate(factors):
    print(f"Factor {i}:\n", factor)


CP decomposition factors:
Factor 0:
 tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
Factor 1:
 [<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.6827860e+01, -1.5862721e+00, -1.2653184e-06],
       [ 4.4119095e+01, -5.1709586e-01, -2.4378679e-07],
       [ 6.1410362e+01,  5.5207729e-01,  7.7774240e-07]], dtype=float32)>, <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.47385353,  1.545288  , -7.145926  ],
       [ 0.5722679 ,  1.185217  , -5.1352615 ],
       [ 0.6706824 ,  0.8251465 , -3.1245954 ]], dtype=float32)>, <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 5.7870436e-01,  2.6729801e+00,  2.1645564e+04],
       [ 6.0184598e-01,  1.5100015e+00, -2.1562041e+05],
       [ 6.2498826e-01,  3.4707579e-01, -4.5287281e+05]], dtype=float32)>]
